export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";

//Pickup
export const ORDER_PICKUP_REQUEST = "ORDER_PICKUP_REQUEST";
export const ORDER_PICKUP_SUCCESS = "ORDER_PICKUP_SUCCESS";
export const ORDER_PICKUP_FAIL = "ORDER_PICKUP_FAIL";
export const ORDER_PICKUP_RESET = "ORDER_PICKUP_RESET";

//Laundry
export const ORDER_LAUNDRY_REQUEST = "ORDER_LAUNDRY_REQUEST";
export const ORDER_LAUNDRY_SUCCESS = "ORDER_LAUNDRY_SUCCESS";
export const ORDER_LAUNDRY_FAIL = "ORDER_LAUNDRY_FAIL";
export const ORDER_LAUNDRY_RESET = "ORDER_LAUNDRY_RESET";
